blueprint:
  name: Demand Control - Notify when actuator becomes unavailable
  description: |
    Send a mobile notification when the Demand Control actuator entity becomes unavailable.
  domain: automation
  input:
    actuator_unavailable_entity:
      name: Actuator Unavailable sensor
      description: Binary sensor from Demand Control (for example sensor.demand_control_actuator_unavailable)
      selector:
        entity:
          domain: sensor
    notify_device:
      name: Notification device
      description: Mobile device to send the notification to.
      selector:
        device:
          integration: mobile_app
    notification_title:
      name: Notification title
      default: "Demand Control"
      selector:
        text:
    notification_message:
      name: Notification message
      default: "EV charge current actuator is unavailable!"
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input actuator_unavailable_entity
    to: "True"

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: !input notification_title
    message: !input notification_message
